### PR TITLE
D8+Composer: Remove obsolete files.

### PR DESCRIPTION
**Pull request by floretan**
There are still many files in the 8.x-composer branch that are only needed for a drush makefile-based build system. I was walking through the process with a colleague earlier and realized that these files are actually just confusing, so it makes sense to remove them.

### CODE REVIEW

**Comment by pjcdawkins** [comment]
How is this going to work without a settings.php, on platform.sh where those files are not writable?

**Comment by floretan** [comment]
That's correct. In the 8.x-composer branch there is already a settings.php under web/sites/default/settings.php though, so the one in the project root is a duplicate.

**Comment by pjcdawkins** [comment]
They are not quite duplicates: I notice the settings.php in web/sites/default is not quite up-to-date with changes in the [drupal/8.x](https://github.com/platformsh/platformsh-examples/tree/drupal/8.x) example. Particularly:
https://github.com/platformsh/platformsh-examples/commit/52f7c62c567a1f10cd22ca19dcc0b4af7cd0a1a0#diff-3a8270dae2b17999b935edc868c22ceb

Without CONFIG_SYNC_DIRECTORY, Drupal will insist on writing to the settings.php during installation. 

IMO... I also don't think we should preserve all the comments; it makes the file unreadable. The commands can stay in default.settings.php.

**Comment by floretan** [comment]
Thanks for the feedback. I updated the settings.php in web/sites/default/settings.php to include the changes related to the sync folder. 

I agree with the comments being unnecessary, but any Drupal developer will be familiar with this file (and it's also a file that is almost never edited in a project). I would do the clean-up in a separate issue.

It would be great to have this issue committed, as we are using the 8.x-composer branch as the default setup for all new projects.

**Comment by pjcdawkins** [comment]
OK, many thanks for this

**Pull request merged**
